### ISSUE TITLE
Experiments on PASCAL VOC

### ISSUE THREAD

**Issue by buncybunny** [thisisi3/OpenMMLab-IoUNet#1]
Hey there.

I transformed your code a bit and trained on PASCAL VOC, seems like mAP is worse than the vanilla Faster R-CNN.
Have you done any experiments on PASCAL VOC too?

**Comment by thisisi3** [comment]
Yes, I did experiments on VOC first. 
My note shows IoUNet's mAP is 45.9 which is better than FasterRCNN's 43.5. The training set is VOC07.
For VOC, it is quite sensitive to the value of lambda, try to increase it to, say 1.0, 2.0.

**Comment by buncybunny** [comment]
@thisisi3 oh the `lamb` in the test cfg. K, will try. Thanks for the reply.
